# Generated by Django 5.0.6 on 2024-07-11 17:01
from django.db import migrations

def add_initial_data(apps, schema_editor):
    Recipe = apps.get_model('api', 'Recipe')

    recipe1 = Recipe(
        name="Spaghetti Bolognese",
        image_url="https://example.com/spaghetti.jpg",
        instructions="1. Cook the pasta. 2. Prepare the sauce. 3. Combine and serve."
    )
    recipe1.save()

    recipe2 = Recipe(
        name="Chicken Curry",
        image_url="https://example.com/chicken-curry.jpg",
        instructions="1. Cook the chicken. 2. Prepare the curry sauce. 3. Combine and serve."
    )
    recipe2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
